inherit_gem:
  fablicop:
    - 'config/.base_rubocop.yml'

AllCops:
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
    - 'db/schema.rb'

RSpec/InstanceVariable:
  Enabled: false

Rails/Output:
  AutoCorrect: false

Metrics/AbcSize:
  Max: 24

RSpec/MultipleMemoizedHelpers:
  Enabled: false
