version: "3"

volumes:
  osm-pgdata:
  osm-tiles:
  valhalla_tiles:
  nominatim-data:

services:
  app:
    build: ./
    volumes:
      - type: bind
        source: "./db"
        target: "/app/db"

  prod-proxy:
    image: nginx:latest
    ports:
      - "3009:80"
    volumes:
      - type: bind
        source: "./vendor/docker/prod-proxy/nginx.conf"
        target: "/etc/nginx/nginx.conf"

  dev-proxy:
    image: nginx:latest
    ports:
      - "3001:80"
    volumes:
      - type: bind
        source: "./vendor/docker/dev-proxy/nginx.conf"
        target: "/etc/nginx/nginx.conf"

  openstreetmap-tile-server:
    build: ./vendor/docker/openstreetmap-tile-server/
    volumes:
      - osm-pgdata:/var/lib/postgresql/12/main
      - osm-tiles:/var/lib/mod_tile
      - type: bind
        source: "./japan-latest.osm.pbf"
        target: "/data.osm.pbf"

  valhalla:
    build: ./vendor/docker/valhalla/
    volumes:
      - "valhalla_tiles:/data"
      - type: bind
        source: "./japan-latest.osm.pbf"
        target: "/data.osm.pbf"

  nominatim:
    image: mediagis/nominatim:3.7
    environment:
      - PBF_PATH=/nominatim/data.osm.pbf
      - REPLICATION_URL=https://download.geofabrik.de/asia/japan-updates/
    volumes:
      - "nominatim-data:/var/lib/postgresql/12/main"
      - type: bind
        source: "./japan-latest.osm.pbf"
        target: "/nominatim/data.osm.pbf"
