// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import DayMapController from "./day_map_controller"
application.register("day-map", DayMapController)

import DayWaypointsController from "./day_waypoints_controller"
application.register("day-waypoints", DayWaypointsController)

import WaypointsController from "./waypoints_controller"
application.register("waypoints", WaypointsController)
