// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import DaysController from "./days_controller"
application.register("days", DaysController)

import WaypointsController from "./waypoints_controller"
application.register("waypoints", WaypointsController)
