tiles:
  endpoint: http://localhost:3001/tiles/tile/{z}/{x}/{y}.png
  attribution: Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors
routing: http://localhost:3001/routing
search: http://localhost:3001/search
