name: Docker image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  image-build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: docker compose build
